apiVersion: v1
kind: Service
metadata:
  labels:
    type: canary
  name: demoapp-canary
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    type: canary
  sessionAffinity: None
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demoapp-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: canary
    spec:
      containers:
      - name: demoapp-canary
        image: bitspradp/cd_demo_spin:BUILD_NUMBER
        ports:
        - containerPort: 5000
        readinessProbe:
            httpGet:
                path: /ping
                port: 5000
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

  strategy:
    type: Recreate
